---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myflatin/test.buildingadmin.myflatinfo.com/

    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH

    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH