-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsJhsYZMAmxqUvfja
/TmhA8WaaA8/yA/xnSjQtNP833KgCgYIKoZIzj0DAQehRANCAATxIMVz4K6wQ+5Q
9kTnQtbORfizs0OM4KHJ1uWfD7QzfoU1a5Inua83JqNlRIwK5nXbbAmAGc5BMipU
TGyJsfKy
-----END PRIVATE KEY-----